services:
  shelf:
    image: ghcr.io/chrisser73/shelf:latest
    platform: linux/arm64
    container_name: shelf
    ports:
      - "18888:18888"
    environment:
      CERT_SAN: ${CERT_SAN}
    volumes:
      - ./data:/data
    restart: unless-stopped
